### ISSUE TITLE
Define color palette based on logo and ideas

### ISSUE THREAD

**Issue by dcruzb** [CollabCity/CollabCity#12]
We must define a color palette to start developing the prototype!

We have ideas, a [logo](https://github.com/CollabCity/CollabCity/blob/main/Logo/CollabCity%20Logo.png), and a [base project](http://collab-city.vercel.app/).

CollabCity is a place where everyone is able to collaborate with other people in the City. You can find places that need donations (e.g. furniture, clothes, monetary or volunteers), and if you need aid you can find someone to help you!

The intention is to build a site to help people maintained by the people!

Feel free to improve as you want!

**Comment by dcbCIn** [comment]
Hi @BellatrixLestrangee, sure, I would love to hear! Do you want me to assign this issue to you?
